version: '3.8'
name: microservice-app

services:
  discovery:
    image: <nombre-usuario>/microservice-app-discovery-server
    container_name: discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - mechanic-net

  gateway:
    image: <nombre-usuario>/microservice-app-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      URL_FRONT: <URL_FRONT>
    networks:
      - mechanic-net

  main:
    image: <nombre-usuario>/microservice-app-principal-service
    container_name: principal-service
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/<name_database>
      URL_FRONT: <URL_FRONT>
    depends_on:
      - db
      - gateway
      - discovery
    networks:
      - mechanic-net

  order:
    image: <nombre-usuario>/microservice-app-order-service
    container_name: order-service
    restart: on-failure
    depends_on:
      - monguito
      - gateway
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      MONGODB_URI: mongodb://<user>:<password>@monguito:27017/<name_database>?authSource=admin&retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000
    networks:
      - mechanic-net
      - monguito-net

  db:
    restart: always
    image: <nombre-usuario>/microservice-app-mysql-main
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: <root_password>
      MYSQL_DATABASE: <name_database>
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mechanic-net

  monguito:
    image: <nombre-usuario>/microservice-app-mongodb-order
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: <password>
      MONGO_INITDB_ROOT_PASSWORD: <name_database>
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - monguito-net

volumes:
  mysql_data:
  mongo_data:

networks:
  mechanic-net:
    driver: bridge
  monguito-net:
    driver: bridge