name: Build and Push Order Service

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/order-service/**'
      - '.github/workflows/order-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Order Service image
        uses: docker/build-push-action@v3
        with:
          context: ./microservices/order-service
          file: ./microservices/order-service/Dockerfile
          push: true
          tags: guillermopalacios/microservice-app-order-service